project:
  name: macMini2.0.0
  output_dir: ./data
  experiment_type: Classification
  subjects_or_events: subjects
  artifact_removal: None
  config_name: config_macmini2.0.0_09-08-2025_1751.yaml
  deployment_method: 'Singularity without Slurm'
data_input:
  groups:
    alz:
      - /Volumes/CrucialX6/Home/bigData/ds004504-download/sub-001/eeg/sub-001_task-eyesclosed_eeg.set
  reuse_processed_subjects: 'No'
  save_processed_subjects: 'No'
  reuse_transformed: 'No'
  save_transformed: 'Yes'
preprocessing:
  bands:
    Delta:
      - 0.5
      - 4
    Theta:
      - 4
      - 8
    Alpha:
      - 8
      - 12
    Beta:
      - 12
      - 30
  window_size: 3.0
  sliding_window: 0.5
  reject_by_annotation: 'Yes'
  downsampling: null
  normalize_psd: 'Yes'
feature_extraction:
  method: welch
  features:
    - Band Power (averaged across all channels/bands)
    - Band Power (per channel, averaged across bands)
    - Band Power (averaged across channels, per band) *(not usually used)
  show_intermediate_results: 'No'
  show_intermediate_counts: 'No'
feature_transformation:
  transformations: MinMax scaler
  synthetic: None
data_leakage_prevention:
  strategy: Transform all data together (no split - fastest, and potential data leakage)
pyspark:
  master: '6'
  driver_memory: '6'
  executor_memory: '6'
  executor_cores: '3'
  shuffle_partitions: '8'
ray:
  models:
    - MLP (Neural Network)
    - KNN
    - SVM
  num_trials: '11'
  max_concurrent: '3'
  metric: accuracy
  mode: max
  cv_folds: '6'
  random_state: '43'
